### ISSUE TITLE
TODO [by page]

### ISSUE THREAD

**Issue by ohjay** [ohjay/down-to-split#1]
### Expenses
- [x] Add percentage attribute to Expense
- [x] Convert all costs to %.2f format
- [x] Let users enter unlimited purchases at once (or at least 20)
- [x] Let users specify vendor and cost split (per group of purchases)
- [ ] Set up live search for vendor (select from list or create new)
- [ ] Set up live search for product (select from list or create new)
- [x] Set up live search for users to split with (select from FRIENDS?)
- [x] Display a list of previous expenses
- [ ] Display visualizations and useful statistics (average amount spent per week/month/etc.)
- [x] Re-add "no users found" if the only search output is yourself
- [x] Allow multiple searches for the final user selection
##### If the user is signed in:
- [x] Display list of what you're owed
- [x] Display list of who **you** owe
- [x] Zeros and closed debts should not be shown
- [x] Allow **person owed** (person owed, ONLY) to enter how much they were paid / close debt
- [x] "Cancel out" debt in situations where A owes B and B owes A
- [ ] Link to history of closed debts
### Price Comparison
- [x] Add seed data for vendors (Trader Joes, Berkeley Bowl, Safeway, etc.)
##### Product Search:
- [ ] Allow **anyone** to search for a product
- [ ] For each search result, display average prices offered by each vendor
- [ ] Highlight best price among those offered
##### Vendor Search:
- [ ] Allow people to see **all listings** from a vendor
- [ ] Allow people to sort that listing by name or by price (analogous to Finder sorting interface)
##### (Optional)
- [x] ~~Allow reviews for each product (so users can see whether the apples were moldy or not)~~
### Login
- [x] Fix sign-in (for some reason it doesn't work now)
### Register
- [x] Auto-select "username" instead of "email"
- [x] Allow users to enter their weekly budget upon registration (optional?)
### Profile
- [x] Allow users to change settings (email, weekly budget, password)
- [x] ~~Allow users to change privacy settings (ex. searchable or nah?)~~
### Miscellaneous
- [x] Add a "Terms of Service" and a "Privacy Policy" section
- [x] Link above sections in footer
- [x] Revamp header/navbar? I wasn't planning for this to be final, but who knows
- [x] Deploy to a production server (Heroku, most likely)
- [x] Add the "sign in" display to the Expenses/Debt Listings tabs
- [x] Make the flash messages (ex. "you have signed in") look better
